name: "Build, Test, Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Build"
        run: |
          echo "Building..."
      - name: "Test"
        run: |
          echo "Testing..."

  deploy-to-staging:
    uses: vanmumuuu-organization/deployment-to-environments/.github/workflows/deploy-to-staging.yaml@main
    needs: [build-and-test]
    if: github.ref_name == 'main'

  deploy-to-production:
    uses: vanmumuuu-organization/deployment-to-environments/.github/workflows/deploy-to-production.yaml@main
    needs: [deploy-to-staging]
    if: github.ref_name == 'main'
