name: "Deploy to Staging"

on:
  workflow_call:

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to Staging"
        run: |
          echo "Deploying to Staging..."
