name: "Deploy to Production"

on:
  workflow_call:

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "Deploy to Production"
        run: |
          echo "Deploying to Production..."
