name: "Run E2E Tests"

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to run E2E tests against"
        type: string
        required: true

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    concurrency: ${{ inputs.environment }}
    steps:
      - name: "Run E2E Tests"
        run: |
          echo "Running E2E tests on ${{ inputs.environment }}"
